import { btoe, etob } from '.';

const textEncoder = new TextEncoder();

/** Pads array with zeros to the nearest byte */
const pad = (arr: Uint8Array) => {
    const padding = 8 - (arr.length % 8);
    if (padding < 8) {
        const padded = new Uint8Array(arr.length + padding);
        padded.set(arr, 0);
        padded.set(new Uint8Array(padding), arr.length);
        return padded;
    }
    return arr;
};

const sentences = [
    'Despite the rain, I went for a walk and enjoyed the peaceful sound of water droplets tapping against my umbrella.',
    'As a child, I used to love climbing trees and feeling the wind in my hair as I reached the top.',
    'In my opinion, one of the most beautiful sights in nature is a waterfall cascading down a rocky cliff.',
    "Whenever I'm feeling down, I like to put on some music and dance around my room to lift my spirits.",
    "Even though it's difficult, I try to stay positive and find the silver lining in every situation.",
    "Without a doubt, spending time with loved ones is one of life's greatest joys.",
    'As a writer, I often find myself lost in my own thoughts and lost in the world of my imagination.',
    'With each passing year, I grow more grateful for the simple pleasures in life, like a warm cup of tea and a good book.',
    'Despite my fear of heights, I love the feeling of soaring through the air on a rollercoaster.',
    'From the moment I wake up, I try to live each day with intention and purpose.',
    'As an artist, I find inspiration in the beauty and complexity of the world around me.',
    'Without hesitation, I would choose a life of adventure and exploration over a life of comfort and predictability.',
    'Despite the chaos of the world around us, I believe that there is still so much beauty and kindness in humanity.',
    "As a student, I've learned that failure is not the end, but simply a chance to learn and grow.",
    'Even though we are all different, I believe that we are all connected by the thread of humanity.',
    'With each passing day, I try to become a better version of myself and make a positive impact on the world.',
    "Without the support of my friends and family, I wouldn't be where I am today.",
    'From the depths of despair, I have learned that hope and resilience are powerful forces that can conquer even the darkest of times.',
    'As a traveler, I am constantly amazed by the diversity and beauty of the world we live in.',
    "Despite the challenges and setbacks I've faced, I remain hopeful and determined to achieve my dreams.",
].map((sentence) => pad(textEncoder.encode(sentence)));

const output = [
    'WAY NET SILK ROUT WU GREW DOCK US ACHE SUIT GEL MANY NIT ANN ACHE TOWN BEST SAN JO PEW SINE TIN ETC SHY BUSS CARD OLIN NECK SWAY DUN CHAW DINE HUCK UTAH BENT EAR DOCK US ACHE SNUB BELT LOGE CHAW PI BOHR TIP REB MIKE DADE JOY HOP RANK BID LOAF DOCK NET GAGE ONTO MAE MASK CREW NEW HUT TIP WOW MASS DAWN ALSO HOLT TIN GEE LOAD COIL DINT SITE TIN SCAR GREW DOOR CORD HULK QUAD OBEY OVA OAR A A A A ACT',
    'TOM HOBO GYP TIN RAT POT CREW KAY BOG HACK BIB MEEK CHAW JOY ICY SLAM BEG RIM DRAB MOD HAM SEEN HERB LOAM COIL DIME OLIN TELL LUG LORD DIME ARC BOLT OMEN BE PEG CHAW CARD BOLT REID BIB PIT CHAR AS SHED SINK TOY POP CURT ARM BRAE TIN FRAY LURK DELL ARC BOON TIE HAAG RUE CHAW COD SHAW QUAD TOY SAG COAT MOD ICY SLID APT ABE',
    'AGEE DEAN HOB URGE BEN MAST COIL DINE BONA SILO NASH RIG DADE MOD HOP RANK BIB PO CHAR ARM BONA TAIL TOY OX CHAW COP BORE ROTH CLAN MAIL JO HOVE BLUE ROBE YET GREY COIL DEAN HOE NEED YOU MEAL CHAR ARK BOON TIN ETC SET BUSS JUDD BOOK RATE GET RAN JO HIT BOON OBEY GAY POW DADE RUB HAP SLID DREW DUE BURY ART HUCK OBEY MARK GREW CARE CARD BLOT RANK SLUR ABE',
    'BIAS US BOLT QUIT CHOW MEAT JIM AFAR SHUT TIN CHOW LORE CREW ALSO HOLT TIN YEA MIND CURT BURT EVE TIN NUMB MADE CHAR AS HOP TIP BIB MENU JO EMIL GAGE TACT WALT LORE JO COVE BOON ROTH PAP OUT DADE JOY HAP NECK SWAT LORE JO COO HUCK THUD SWAY DUG CULT ONUS HUH SLEW WALT GREY DOCK EACH HIT ROTH CLAN DUG CULT ONUS HUT SNUB HERO POP DOCK HOLD FILE A A ACT',
    'WIN LOUD BOLT TIP YAP RID DOOR SEE BOG ROUT TUG MEEK JO LAW BLOT RATE HEEL MICE CREW JIBE BOG HACK BIB RUM EARL AS HOP TIP RET OVA EARL ART HOP TACT HERS POT DRAB MOD GYP SINK TOY PET COIL DIME BOG TEET FREE GREY DING ALSO ILL QUIT KIM RAM COIL DINE BOLT REID BED MARE JO NEW HOFF SULK HAAG RYE COIL JUJU BING TEET HERD MANY OAR A A A A ACT',
    'BIAS ALUM HER SLID BHOY DUE BURY ARE HOP THUD MAP GAP JO HOWL HAT SINK YAP MANN CLAM AS HEY SHOE BAND SHE COIL JUDE BOG SEEN WARD PEA CASK ARM SIDE QUIT PAP POW DIME ARM SIDE OVEN BEN LOST JO CARD BLOT OVEN DRUG GREW CLAW HALT BING TEET BETH MEMO JO BASH SLAM SWAY SLUR ACT',
    'TOM HOBO GYP TIP DRUG POP DOCK NET GIBE TIE HAAG RIM CHUB JUDD BOLT TIN CHUG MARC CASK ARM BRAE TACT BESS PEP JO CARE SINK TEAR BED MANY JO COWL ACHE SLID DREW DUG DOCK VAN SITU RENT FUND RYE JO CON HOBO TIN OBOE MELD DISK ARK BOLT TIP YAP PEG JO MILL SINE SEEN TOY RIM CHOU ARM BRAE TIN HERB LIVE CLAW ALSO HILT TEET HERD MANY OAR A A A A ACT',
    'BIAS ALUM HER TIN BELT LONE CLUE ART GYP TAIL RAT MARE CLAM ASH BLOB NEED LAD DUN AFAR ARE SINE SLID DEFY RAW DARK HALT ACHE REST LOW MEMO CHAW PI BOHR TIN CITY MEAN JO JUDE HAT TIP RAT MANA DAWN CANT ACHE SNUB NUDE LIST DING LAWS HOFF SWAY BED MARE JO CARD BLOT OVEN NASH RAN COIL BOIL ACHE NAVY BID LOAF DENY CODE HAM THUG ANA RIM CHOU AS HAT NAVY BAR MANN CASK ARC ACHE RENT WAND LOOK JO FEE SIGH SAME SLUR A',
    'WAY NET SILK ROUT WU GREW CULT ONUS HAY QUAD GIN EAR DARK OWL HER QUAD HELD LUND DOCK HOLD BOG HACK BEG RID DRAB MOD ICY ROAR BAND PER CHAW NEE HEY SINK DEFY RID CHOU ART SIGH NEED MA MANN CLAM AS HER SUIT WANT LUKE CLUE AS HER OVEN BAR LUSH DELL ARM SIDE TIN ETC RUM DARK CARE HAT SUIT REB LOAF DING JUDD BOOK BONE A ACE',
    'YAM HANG SHUT TIP YAP PEN JO CORN SHUT QUAD TALK DUG AFAR AS SEAT SANK BAND SAY DAVE BURT EVE TIP YET SLY JO JUDO OLIN SEEN HESS PEG JO NAY BLAB RISK BAY OUT EARL AS SHED TEET FLAT POP DADE JUDD BOLT TEET HERD MARC JO CON HOBO TIP BIB MEAD DAWN EMIT SEND BONE A A',
    'TOM HOBO GYP SILO BAR MEAT DOCK ALTO SITE BING AVE GREW CHUB ALSO HOBO TIN HERD SAD DAWN ALTO HILT TEET HERD MANN JO ALSO GAGE TEET FREE GRIM CAKE NAY BORN TELL HAAG OW DADE JOY HAM SLEW SAUL RAN CHAW NEON BORE URGE BEN LOVE JO JUDE HAT TIP DREW MEAN CREW JOY GYP SUIT WANT MANY CASK ARM BLOB BONE A ABE',
    'BIAS ALUM HER SLID BHOY DUE COAT NET SHED TEET GO POW DARK DECK BOG HACK BID MARY DOOR CANT BOG OBEY FUEL MARY DING MOD GYP TIN NUMB LOVE CHAR ARM SETS TIN GAY SEN CHAW DIRE IF SUIT BAND OVA DADE JOY HAT TUNA BEG RID DENY COP HEY SLEW SOME RIG DRAB NET GAGE NAVY BEG POT CHUB MOD HOP RANK BAT MARS CULT PEW SINE TEAR BAR MARE CASK ART HUH QUAD YAP LOIS DOCK COD HOOD SEEN HERS SIT OAR A A A A ACT',
    'WAY NET SILK ROUT WU GREW DOCK US ACHE OBEY FRAY MARS DIME ARM SETS TIP YAP PEA JO MILL SINE SEEN TOY OVA DENY EMMA BOLT OMEN BIB MEEK NIT ANN ACHE NOAH BESS POW CHAW LOUD ACHE TEET FRAY MENU JO JUDE HAT SUIT BAND POE DIME ART SITE ROTH OBEY DUG DING EACH HOB THUD RAT DUE CAKE NAY BORN TELL HAAG OW DADE JOY HIP ROTH SWAY RED CHAW HOWL OLIN ROTH SOME PO DOOR CORD BOLT ROUT ABEL HERS',
    'TOM HOBO GYP TIP RET SAY CAVE NEE HURD BING AVE HARK DRAB MOD HIT QUAD GIN RIB CHAW JOY ICY ROAR GO DUE CHUB COL BOHR THUG LUG GREY COIL HOBO HOE SLID TOY SAG COAT MOD HAT SINK TWO DUE CAKE LAYS BOG TACT HERB MASS CREW ONUS GYP TIN RAT OUT DADE HO ACHE TEET ULAN RAP CHAW COO HOWL TIN GIG PAR JO SET HUCK TORN SLUR ACT',
    'WIN LOUD BOLT TIP YAP RID DOOR SEE BOG TOWN BAND OWE DENY MOD GYP SEEN NASH PAW COIL PER HOFF SUIT BEST SAN NIT ANN ACHE NOAH BESS POW CHAW LOUD ACHE TEET FRAY MENU JO MILE ACHE NEED LUG GRID BUSS CARE BOG OBEY WAND REP CHAW HOG HAT OMEN BAT SLY JO JUDE HAT TIP YAP RUM CHAW COG BOG SLEW CAFE PLY DOOR CORD BOLT ROUT ABEL HERS',
    'BIAS ALUM HER TIN BELT LONE CLUE ART GYP TAIL RAT MARE CLAM ARE GYP URGE NASH LIP JO JUDY IFFY TIP YEA GRID CAKE NAY SIGH SHOE BAND OWE JO FAY BORE TEET BETH EAR DRAB NET HUNK ROTH WAND DUN DARK OWL HOB VAIL RAN MAIN CHOU ARC BOLT OMEN BEG LIVE CORN MOD GYP TIP BEN MEET COIL JUDE BOSS OVEN BED MALI DAWN COD SITE TIN WAND DUE DOCK US ACHE TOWN WANG RAN CASK DATE A A A ACT',
    'BIAS ALUM HER SLID BHOY DUE DOCK US ACHE TAIL BETA ROD DARK HANS BOG SLEW CAFE RAY EARL ARE HULK ROTH BEST PAP DIME ARC BOLT OMEN BE OVA CULT ALSO IRA BING AVE GRIM DUAL EMMA BOHR ONLY SOOT MEMO JO FAY ACHE TOWN FREE MEAN CHAR ANN ACHE NECK ROOM SAN DARK LAM BRAE BONE A ACT',
    'YAM HANG SHUT TIP YAP PEN JO LAP BONE TEET FUME GRID DARK OWL HAP QUIT RED OVA COIL GURU BOG HACK BED OW DRAB MOD HIT QUAD GIN RIB CHAW JOY ICY ROAR GO DUE COAT EMIT HAT TIN GIG PAR JO HALT BOON ROTH NUMB LOSS DADE HO ACHE NEED LUG GRID DAWN EMMA SEND SUIT CLAN MAKE JO PEW SINE OBEY BETH GRIM DOCK UP BORE TIN RAG MARE JO HOC SIDE SOUR BENT MEAT JO NEW HOFF SILO BIB POD CHAR ARE GYP SUIT MAKE MEET DISK ARM SETS TIP YAP MALT CHAW HOLD FILE A A ACT',
    'TOM HOBO GYP TIP YET OUT DRAB NEE HAT STUB NASH LID JO CON ACHE OBEY WAND RYE DOCK CON HURD SEES HAAG OVA CULT COT HOFF OMEN BAT SKY JO JUDE HAT TIN YAP MILD CHAW HANK SHED TELL HAAG OW DADE JOY HAD QUAD GO MERT EARL ARM SETS TIP YAP PEA JO MILL SINE SEEN TOY SEW CHAR ARM HEY TOAD BAND POW CURT DATE A A A ACT',
    'WAY NET SILK ROUT WU GREW DOCK US ACHE OBEY FRAY MAKE CREW NEE HOLT QUIT PAP OUT DADE JOY HUT QUIT WRY OUT CARE BOLT OLIN HACK DUAL PEA JO PEP BLAB QUAD TWO DUN AFAR ART HOFF SHOE GEL MARC JO VAN SILK QUAD CLAN MALE JO CON HOBO TIN WU MENU CHAW HANG BOAT SINK BENT EAR DOCK EACH GYP OBEY FREY LOSE DRAB MOD HOB URGE BAY RUB CHAW CON BOON BONE A ACE',
];

const words =
    'ARTS LAWN HIT NAVY BIB RUE COIL HOYT HEY SOUR BENT GRID DOCK LAWS HUFF ROUT PAP RIP DOOR HANS BOON BING BAR MEND JO LAW BLAB TELL BESS GRID DADE LAWN HIT NAVY BAT MARY DADE LOST BOHR SEEN HERO GRID BUSS HAW GAGE FLOC NUMB MAUL DOOR CON ACHE QUIT LOW MERT JO LOWE SHOW THUG YES OWE DISK DEAN FEW THUD OBEY OW JO COD OLIN TACT WALT RAN COIL HOB BORE THUD YAP MARE JO FOGY BOOK THUG PEG DUN CHAW JERK ICY SUIT HERO MEND COIL GINA BLOB TIN HERE RYE DOOR COIL GAGE FUEL LOW MELT JO HAND HOP SINK RET MEET JO GINA BING SHED BAR LOGE JO PHI HOOD SINK DRAG MALE CREW BUG HUH ROAR WAND PAM DOOR HOLD GAGE JEFF LOW LOSS DING NEE HURD TIN SALK MERT DOCK ALTO OLIN TEET HERD PAL COIL LED BOLT TEAR BEG POW CLAW LAWN GYP BING BAR GREW DING ELLA GYP SEEN BETH GREW CAVE EMIL HOP STUB BEG LOAF DOCK JUDE BOON TIN BHOY HESS JIM ALSO HURD QUAD DOWN MEAN JO JUDE BOLT OBEY HEFT SAY DADE JERK HAT TRUE BEY LURK DISK ARC BOLD QUIT TOY RET CHAW GINA BLOB TIN SALK MAIL CHAW HOYT BING ONLY FAN DUG DING ALUM BOG NECK SAME MEND JO LOUD BOON TEET HEEL SAY CREW LAWN ACHE ROUT BEY MESH CUFF AS HOFF ROAR HEEL MESH CREW BUS GAGE HUNT BESS RAP BURY ARE HILT OBEY HERB POE DING AGEE FILE A A A';
const wordArray = words.split(' ');

describe('rfc1751', () => {
    it('correctly encodes data', () => {
        for (let i = 0; i < sentences.length; i++) {
            expect(btoe(sentences[i])).toEqual(output[i]);
        }
    });

    it('correctly decodes data', () => {
        for (let i = 0; i < sentences.length; i++) {
            expect(etob(output[i])).toEqual(pad(sentences[i]));
        }
    });

    it('throws error on words that are not a multiple of 6', () => {
        const wrongWords = [...wordArray];
        const throwable = () => {
            return etob(wrongWords.join(' '));
        };

        wrongWords.splice(0, 1); // Delete one word to make it not a multiple of 6
        expect(throwable).toThrow('Parity error at COIL');

        wrongWords.splice(0, 4);
        expect(throwable).toThrow('Parity error at PAP');

        wrongWords.splice(0, 1); // Back to a multiple of 6
        expect(throwable()).toBeTruthy();
    });

    it('throws error on words that are not compliant', () => {
        const wrongWords = [...wordArray];
        const throwable = () => {
            return etob(wrongWords.join(' '));
        };

        wrongWords.splice(0, 1, 'SOMETHING'); // Delete one word and insert custom data
        expect(throwable).toThrow(
            'Words must be between 1 and 4 characters long'
        );

        wrongWords.splice(0, 1, 'ANOTHER');
        expect(throwable).toThrow(
            'Words must be between 1 and 4 characters long'
        );

        wrongWords.splice(0, 1, '');
        expect(throwable).toThrow(
            'Words must be between 1 and 4 characters long'
        );
    });
});
